version: "3.5"
services:
  capp:
    build: ./
    container_name: capp
    restart: always
    ports:
      - 8080:80
    volumes:
      - ~/Downloads/tmp/src:/var/www/html

  cdb:
    image: mysql/mysql-server:latest
    container_name: cdb
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./server/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
